repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      # Run the Linter (Fixes simple errors automatically)
      - id: ruff
        args: [ --fix ]
      # Run the Formatter (Makes code look pretty)
      - id: ruff-format